# apiVersion: v1
# kind: Pod
# metdata:
#   name: static-web
#     labels:
#       role: myrole
# spec:
#   containers:
#     - name: web
#       image: nginx
#       ports:
#         - name: web
#           containerPort: 80
#           protocole: TCP

apiVersion: app/v1
kind: ReplicaSet
metdata:
  name: frontend
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    matchlabels:
      tier: frontend
  template:
    metdata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: webserver
          image: nginx