version: '3.3'

services:

  db:
    build: db
    image: symilian9976/db:1.0.0
    
  front:
    build: front
    image: symilian9976/front:1.0.0
    ports:
    - "8083:80"

  words:
    build: back
    image: symilian9976/back:1.0.0
