name: Docker Build

on:
  push :
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu:latest

    steps:
    - run: actions/checkout@v3
    - run: docker build -t back .
      working-directory: back
    
    - run: docker --help
