name: Docker push

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: "cloud_native_bakowski_maximilien"
      ACTOR: "symilian8876"
      
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_NAME }}/back:1.0.0 .
      working-directory: back
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password : ${{ secrets.GITHUB_TOKEN }}

    - name: Push the image
      run: docker push ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_NAME }}/back:1.0.0
      
    - name: build and push
      uses: docker/build-push-action@v4
      with:
        context: back
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.ACTOR }}/${{ env.IMAGE_NAME }}/back:1.0.0

